import {
  FileProtectOutlined,
  CarOutlined,
  ShopOutlined,
  AppstoreOutlined,
  FileTextOutlined,
  FileAddOutlined,
  BarChartOutlined,
  CalendarOutlined,
  SettingOutlined,
  HomeOutlined,
  TeamOutlined,
  ProfileOutlined,
  PlusOutlined,
  DesktopOutlined,
  ThunderboltFilled,
  BellOutlined,
  MailOutlined,
  CheckSquareOutlined,
  SafetyCertificateOutlined,
  LockOutlined,
  ApartmentOutlined,
  NotificationOutlined,
  CloudOutlined,
  BlockOutlined,
  ApiOutlined,
  CloudServerOutlined,
  DeploymentUnitOutlined,
  FundProjectionScreenOutlined,
  DashboardOutlined,
  AuditOutlined,
  UserOutlined,
  RocketOutlined,
  CopyOutlined,
  LinkOutlined,
  DownloadOutlined,
  PlayCircleOutlined,
  CheckOutlined,
  CloseOutlined,
  SearchOutlined,
} from '@ant-design/icons'
import type { ReactNode } from 'react'

const map: Record<string, ReactNode> = {
  FileProtect: <FileProtectOutlined />,
  Car: <CarOutlined />,
  Shop: <ShopOutlined />,
  Appstore: <AppstoreOutlined />,
  FileText: <FileTextOutlined />,
  FileAdd: <FileAddOutlined />,
  BarChart: <BarChartOutlined />,
  Calendar: <CalendarOutlined />,
  Setting: <SettingOutlined />,
  Home: <HomeOutlined />,
  Team: <TeamOutlined />,
  Profile: <ProfileOutlined />,
  Plus: <PlusOutlined />,
  Monitor: <DesktopOutlined />,
  Thunderbolt: <ThunderboltFilled />,
  Bell: <BellOutlined />,
  Mail: <MailOutlined />,
  CheckSquare: <CheckSquareOutlined />,
  Safety: <SafetyCertificateOutlined />,
  Lock: <LockOutlined />,
  Apartment: <ApartmentOutlined />,
  Notification: <NotificationOutlined />,
  Cloud: <CloudOutlined />,
  Block: <BlockOutlined />,
  Api: <ApiOutlined />,
  CloudServer: <CloudServerOutlined />,
  Deployment: <DeploymentUnitOutlined />,
  FundProjectionScreen: <FundProjectionScreenOutlined />,
  Dashboard: <DashboardOutlined />,
  Audit: <AuditOutlined />,
  User: <UserOutlined />,
  Rocket: <RocketOutlined />,
  Copy: <CopyOutlined />,
  Link: <LinkOutlined />,
  Download: <DownloadOutlined />,
  Play: <PlayCircleOutlined />,
  Check: <CheckOutlined />,
  Close: <CloseOutlined />,
  Search: <SearchOutlined />,
}

export default function IconByName({ name, style }: { name?: string; style?: React.CSSProperties }) {
  if (!name) return <AppstoreOutlined style={style} />
  return <span style={style}>{map[name] ?? <AppstoreOutlined />}</span>
}